# Generated by Django 5.2.12 on 2026-03-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
